### ISSUE TITLE
Running ccslint on codeclimate CLI crashes oddly

### ISSUE THREAD

**Issue by jhmilan** [codeclimate/codeclimate-csslint#2] opened 2015-06-25 20:54 UTC
It is being impossible to me running csslint with codeclimate.

### setup
This is my local setup

* Mac OS X 10.10.3 (Yosemite)
* boot2docker 1.7.0
* codeclimate CLI 0.0.8 (installed the brew package)
* bash 4.3 (this is not important it worked exactly the same with 3.2 but I had to upgrade it by other reasons)

### codeclimate config

This is my .codeclimate.yml file

```
---
engines:
  phpcodesniffer:
    enabled: false
  coffeelint:
    enabled: false
  eslint:
    enabled: true
  csslint:
    enabled: false
ratings:
  paths:
  - "**.php"
  - "**.js"
  - "**.css"
exclude_paths:
- "node_modules/**/*"
- "vendor/**/*"
- "etc/**/*"
- ".vagrant/**/*"
```

I run `composer analyze` and this is the result:

```
 codeclimate analyze
Starting analysis
Running csslint: \Error deleting container: Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
An error occurred trying to connect: Post https://192.168.59.103:2376/v1.19/containers/acbef0423c3c1cdd9aaa07fe2de1d47b3f052eb8991e0a443e07b8dfa95944bb/wait: EOF

```

After that the only possible solution is `boot2docker restart`. Other engines (phpcodesniffer) works. Any help?

**Comment by ABaldwinHunter** [comment] 2015-06-25 21:35
Hi @jhmilan. Sorry you had that issue. It seems like docker might have died in between engine analyses. Could you try running `phpcodesniffer` again to make sure docker is running and let me know the result?

**Comment by jhmilan** [comment] 2015-06-25 21:43
@ABaldwinHunter yes.

After that fail, I change the yml file to enable phpcodesniffer and disable cssling. Output here:

```
bash-4.3$ boot2docker restart
bash-4.3$ codeclimate analyze
Starting analysis
Running phpcodesniffer: Done!

Analysis complete! Found 0 issues.
```

Whenever I re-enable csslint it crashes again :|

**Comment by jhmilan** [comment] 2015-06-26 07:19
I'm assuming the "ratings:" "paths" say codeclimate what to explore.

It takes a long while and looks like it exhuast memory. I did a small test only providing a single small file within this paths and same result. Long analysis + crash. Quite odd.

**Comment by ABaldwinHunter** [comment] 2015-06-26 15:55
Hmm @jhmilan thanks for the update! I'm not sure whether the problem is docker related. Can you try running 
```
codeclimate engines:enable csslint
codeclimate engines:enable eslint
codeclimate engines:enable phpcodesniffer
codeclimate engines:enable coffeelint
codeclimate analyze
``` 
and paste the result?

Also, if you're able to share a test repo with the example you're using, I'd be happy to take a look.

**Comment by jhmilan** [comment] 2015-06-26 17:56
Here I go:

```
$ codeclimate engines:enable csslint
Engine already enabled.
Pulling docker images.
latest: Pulling from codeclimate/codeclimate-csslint
3f15d96b17e2: Pull complete 
a26a18d88e20: Pull complete 
8cd499aa45b2: Pull complete 
4ef858b6cc8d: Pull complete 
c63140442092: Pull complete 
93904b6ec726: Pull complete 
dd7c6416b161: Already exists 
30fdd4801977: Already exists 
4b290ff51a29: Already exists 
Digest: sha256:6a07109139433b161561ff457b68fff88d02402f318aeff33d3c3f035e2a5aa3
Status: Downloaded newer image for codeclimate/codeclimate-csslint:latest
```

```
$ codeclimate engines:enable eslint
Engine added to .codeclimate.yml.
Pulling docker images.
latest: Pulling from codeclimate/codeclimate-eslint
b7bcdc5241b7: Pull complete 
4f8bdcd5f41f: Pull complete 
7f96483f258e: Pull complete 
2754fbba38f0: Already exists 
30fdd4801977: Already exists 
4b290ff51a29: Already exists 
c6efac97c88b: Already exists 
7c5355228f97: Already exists 
Digest: sha256:15ad4678ab32f48d871b5bc6a6206a583f89f1a2a3f41555c123d56ee70be7fd
Status: Downloaded newer image for codeclimate/codeclimate-eslint:latest
latest: Pulling from codeclimate/codeclimate-csslint
30fdd4801977: Already exists 
4b290ff51a29: Already exists 
3f15d96b17e2: Already exists 
a26a18d88e20: Already exists 
8cd499aa45b2: Already exists 
4ef858b6cc8d: Already exists 
c63140442092: Already exists 
93904b6ec726: Already exists 
dd7c6416b161: Already exists 
Digest: sha256:6a07109139433b161561ff457b68fff88d02402f318aeff33d3c3f035e2a5aa3
Status: Image is up to date for codeclimate/codeclimate-csslint:latest
```

```
$ codeclimate engines:enable phpcodesniffer
Engine added to .codeclimate.yml.
Pulling docker images.
latest: Pulling from codeclimate/codeclimate-phpcodesniffer
738a1bfe5338: Pull complete 
1c3897630380: Pull complete 
dc189ed7b184: Pull complete 
10b97f19b106: Already exists 
49781c56e8e7: Already exists 
ee161c93d680: Already exists 
74270a87e940: Already exists 
3cacb3e4507e: Already exists 
9352a9d4c543: Already exists 
Digest: sha256:9ff0db6032503d4ebf7fbfe28d263e241aa44803ee22e2235f151aa27a5f9697
Status: Downloaded newer image for codeclimate/codeclimate-phpcodesniffer:latest
latest: Pulling from codeclimate/codeclimate-eslint
30fdd4801977: Already exists 
4b290ff51a29: Already exists 
c6efac97c88b: Already exists 
7c5355228f97: Already exists 
b7bcdc5241b7: Already exists 
4f8bdcd5f41f: Already exists 
7f96483f258e: Already exists 
2754fbba38f0: Already exists 
Digest: sha256:15ad4678ab32f48d871b5bc6a6206a583f89f1a2a3f41555c123d56ee70be7fd
Status: Image is up to date for codeclimate/codeclimate-eslint:latest
latest: Pulling from codeclimate/codeclimate-csslint
30fdd4801977: Already exists 
4b290ff51a29: Already exists 
3f15d96b17e2: Already exists 
a26a18d88e20: Already exists 
8cd499aa45b2: Already exists 
4ef858b6cc8d: Already exists 
c63140442092: Already exists 
93904b6ec726: Already exists 
dd7c6416b161: Already exists 
Digest: sha256:6a07109139433b161561ff457b68fff88d02402f318aeff33d3c3f035e2a5aa3
Status: Image is up to date for codeclimate/codeclimate-csslint:latest
```

```
$ codeclimate engines:enable coffeelint
Engine added to .codeclimate.yml.
Pulling docker images.
latest: Pulling from codeclimate/codeclimate-phpcodesniffer
49781c56e8e7: Already exists 
ee161c93d680: Already exists 
74270a87e940: Already exists 
3cacb3e4507e: Already exists 
9352a9d4c543: Already exists 
738a1bfe5338: Already exists 
1c3897630380: Already exists 
dc189ed7b184: Already exists 
10b97f19b106: Already exists 
Digest: sha256:9ff0db6032503d4ebf7fbfe28d263e241aa44803ee22e2235f151aa27a5f9697
Status: Image is up to date for codeclimate/codeclimate-phpcodesniffer:latest
latest: Pulling from codeclimate/codeclimate-coffeelint
bfb2d4b75c8c: Pull complete 
c15596cd9876: Pull complete 
f59b662afb38: Pull complete 
fd6aca9ecdcc: Pull complete 
3cfb2ef3d438: Pull complete 
017e898257a5: Pull complete 
3a70f84c1fb0: Already exists 
30fdd4801977: Already exists 
4b290ff51a29: Already exists 
Digest: sha256:c8b52f40fe5b71dba233059fa8cc43767a3d9c33801ee0d8208209ae00db59a9
Status: Downloaded newer image for codeclimate/codeclimate-coffeelint:latest
latest: Pulling from codeclimate/codeclimate-eslint
30fdd4801977: Already exists 
4b290ff51a29: Already exists 
c6efac97c88b: Already exists 
7c5355228f97: Already exists 
b7bcdc5241b7: Already exists 
4f8bdcd5f41f: Already exists 
7f96483f258e: Already exists 
2754fbba38f0: Already exists 
Digest: sha256:15ad4678ab32f48d871b5bc6a6206a583f89f1a2a3f41555c123d56ee70be7fd
Status: Image is up to date for codeclimate/codeclimate-eslint:latest
latest: Pulling from codeclimate/codeclimate-csslint
30fdd4801977: Already exists 
4b290ff51a29: Already exists 
3f15d96b17e2: Already exists 
a26a18d88e20: Already exists 
8cd499aa45b2: Already exists 
4ef858b6cc8d: Already exists 
c63140442092: Already exists 
93904b6ec726: Already exists 
dd7c6416b161: Already exists 
Digest: sha256:6a07109139433b161561ff457b68fff88d02402f318aeff33d3c3f035e2a5aa3
Status: Image is up to date for codeclimate/codeclimate-csslint:latest
```

```
$ codeclimate analyze
Starting analysis
Running phpcodesniffer: Done!
Running coffeelint: Done!
Running eslint: Done!
/usr/lib/ruby/gems/2.2.0/gems/json-1.8.3/lib/json/common.rb:155:in `parse': failed to allocate memory (NoMemoryError)
	from /usr/lib/ruby/gems/2.2.0/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
	from /usr/src/app/lib/cc/analyzer/formatters/plain_text_formatter.rb:16:in `write'
	from /usr/src/app/lib/cc/analyzer/engine.rb:26:in `block (2 levels) in run'
	from /usr/src/app/lib/cc/analyzer/engine.rb:25:in `each_line'
	from /usr/src/app/lib/cc/analyzer/engine.rb:25:in `block in run'
```

Also notice that :

1. Each time I run `codeclimate engines:enable <engine>` my excluded_paths change. I had any of them in qoutes and these qoutes get removed

2. eslint was disabled previously and now enabled but error is the same than in csslint

Thanks

Btw I've just pushed the code here https://github.com/jhmilan/jmilan.net

**Comment by GordonDiggs** [comment] 2015-06-26 18:00
Thank you! Having the code helps - we know of some general issues that might be affecting this. Will look into them and report back!

**Comment by mariozaizar** [comment] 2015-09-04 20:46
I'm experiencing the same issue with a 5 years old rails application. 

```
codeclimate analyze
Unable to find image 'codeclimate/codeclimate:latest' locally
latest: Pulling from codeclimate/codeclimate

49781c56e8e7: Pull complete
1b5514d1d85f: Pull complete
bbb4133ee795: Pull complete
9e8e847d05b8: Pull complete
23f7981987e1: Pull complete
b9cb243814fc: Pull complete
61623d49c6f9: Pull complete
9f8b2b928d65: Pull complete
e5956863b151: Pull complete
9ef13c1f5fb6: Pull complete
8601b4b9ffab: Pull complete
8fb07935b671: Pull complete
34a196b383bd: Pull complete
fd92228677df: Pull complete
5e8addf27cb5: Already exists
Digest: sha256:1cf76ae7b1fe47b788aef7c34ce2da099d641efeef5630e6cb2c1cce980fa1bd
Status: Downloaded newer image for codeclimate/codeclimate:latest
Starting analysis
Running rubocop: Done!
Running golint: Done!
Running gofmt: Done!
Running eslint: Done!
Running csslint: \Error deleting container: Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
```

I'm using Docker version 1.8.1, build d12ea79.

**Comment by gmile** [comment] 2015-10-06 08:27
Similar odd issue here:

```
$ codeclimate analyze
Starting analysis
Running rubocop: Done!
error: (Errno::ENOENT) No such file or directory @ rb_sysopen - /tmp/cc/c60ecc63-ec12-40ec-89f3-25550abbdf1e
```

Latest docker pkg and codeclimate gem.

**Comment by dblandin** [comment] 2016-10-03 16:22
We made some changes in https://github.com/codeclimate/codeclimate-csslint/pull/34 to better handle parsing errors during analysis.

I'm going to go ahead and close this issue for now but feel free to comment if this is still an issue.

**Closed by dblandin** 2016-10-03 16:22 UTC
Labels: pending
